### ISSUE TITLE
Different Dispatch behavior between Py2 and Py3

### ISSUE THREAD

**Issue by ronanpaixao** [pywin32/pypiwin32#55]
I'm trying to write some code to handle the SAP application.

However, I recently migrated my install from Python 2.7 to 3.6 and things started falling apart.

My code is something like:

```
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 19 2016, 13:36:02) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from win32com.client import Dispatch
>>> application = Dispatch("Sapgui.ScriptingCtrl.1")
>>> print(application)
<win32com.gen_py.SAP GUI Scripting API._Dsapfewse instance at 0x71205792>
>>> print(application.Children)
<win32com.gen_py.SAP GUI Scripting API.ISapCollectionTarget instance at 0x71206032>
>>> print(len(application.Children))
0
>>> print(len(Dispatch(application.Children)))
0
>>> Dispatch(application.Children)
<win32com.gen_py.SAP GUI Scripting API.ISapCollectionTarget instance at 0x71468296>
```

`application.Children` belongs to the same type library as `application`. It is a collection, but for some reason it is being treated differently on Python 3:

```
Python 3.6.0 |Anaconda 4.3.0 (32-bit)| (default, Dec 23 2016, 12:06:52) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from win32com.client import Dispatch
>>> application = Dispatch("Sapgui.ScriptingCtrl.1")
>>> print(application)
<win32com.gen_py.SAP GUI Scripting API._Dsapfewse instance at 0x36460272>
>>> print(application.Children)
<win32com.gen_py.None.GuiComponentCollection>
>>> print(len(application.Children))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'GuiComponentCollection' has no len()
>>> print(len(Dispatch(application.Children)))
0
>>> Dispatch(application.Children)
<win32com.gen_py.SAP GUI Scripting API.ISapCollectionTarget instance at 0x58382832>
```

Instead, I have to either use `len(Dispatch(application.Children))` or `application.Children.Count`. This gets ugly very quickly because I have quite some code I'd have to convert and because this need to pass everything through `Dispatch()` is required for *every member of every type I use through COM*.

By the way, I have both Python versions installed by using Anaconda environments (had to install Py2 later to test above code). I have also tried using various forms of static binding (makepy, EnsureDispatch and others).

Looking in the `.py` wrapper generated by makepy, I found this, which suggests that win32com knows the proper type:

```
class _Dsapfewse(DispatchBaseClass):
	CLSID = IID('{93A37525-9118-4731-92A7-B93DF1E34455}')
	coclass_clsid = IID('{B90F32AD-859E-4EDD-BFAE-C9216849520C}')
        ...
	_prop_map_get_ = {
                ...
		# Property 'Children' is an object of type 'GuiComponentCollection'
		"Children": (32019, 2, (13, 0), (), "Children", '{A464F5B4-CC70-4062-A0A1-6DC9B461D776}'),
                ...
	}
	_prop_map_put_ = {
                ...
		"Children" : ((32019, LCID, 4, 0),()),
                ...
	} ...
```

**PS:** some testing suggests that if I *don't run* makepy with Python 3, `len()` works in the collection, even though it breaks elsewhere. Now I'm confused by even more different behavior. This is the same code after excluding makepy-generated files:

```
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:06:52) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from win32com.client import Dispatch
>>> application = Dispatch("Sapgui.ScriptingCtrl.1")
>>> print(application)
<COMObject Sapgui.ScriptingCtrl.1>
>>> print(application.Children)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\u5fs\AppData\Local\Continuum\Anaconda3\envs\auditmed\lib\site-packages\win32com\client\dynamic.py", line 212, in __str__
    return str(self.__call__())
  File "C:\Users\u5fs\AppData\Local\Continuum\Anaconda3\envs\auditmed\lib\site-packages\win32com\client\dynamic.py", line 197, in __call__
    return self._get_good_object_(self._oleobj_.Invoke(*allArgs),self._olerepr_.defaultDispatchName,None)
pywintypes.com_error: (-2147352567, 'Exception.', (618, 'sapfewse', 'Bad index type for collection access.', None, 0, 0), None)
>>> print(len(application.Children))
0
>>> print(len(Dispatch(application.Children)))
0
>>> Dispatch(application.Children)
<COMObject <unknown>>
```

**Comment by xoviat** [comment]
Would you mind trying this on Python 3.5? The version changed when providing the 3.6 wheels, and it would be helpful to know whether this caused these problems.

**Comment by ronanpaixao** [comment]
Testing with Python 3.5.2 (pywin32 still at version 220), before running `makepy`:

```
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:45:57) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from win32com.client import Dispatch
>>> application = Dispatch("Sapgui.ScriptingCtrl.1")
>>> print(application)
<COMObject Sapgui.ScriptingCtrl.1>
>>> print(application.Children)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\u5fs\AppData\Local\Continuum\Anaconda3\envs\auditmed35\lib\site-packages\win32com\client\dynamic.py", line 212, in __str__
    return str(self.__call__())
  File "C:\Users\u5fs\AppData\Local\Continuum\Anaconda3\envs\auditmed35\lib\site-packages\win32com\client\dynamic.py", line 197, in __call__
    return self._get_good_object_(self._oleobj_.Invoke(*allArgs),self._olerepr_.defaultDispatchName,None)
pywintypes.com_error: (-2147352567, 'Exceção.', (618, 'sapfewse', 'Bad index type for collection access.', None, 0, 0), None)
>>> print(len(application.Children))
0
>>> print(len(Dispatch(application.Children)))
0
>>> Dispatch(application.Children)
<COMObject <unknown>>
```

and after running makepy:

```
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:45:57) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from win32com.client import Dispatch
>>> application = Dispatch("Sapgui.ScriptingCtrl.1")
>>> print(application)
<win32com.gen_py.SAP GUI Scripting API._Dsapfewse instance at 0x44036944>
>>> print(application.Children)
<win32com.gen_py.None.GuiComponentCollection>
>>> print(len(application.Children))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'GuiComponentCollection' has no len()
>>> print(len(Dispatch(application.Children)))
0
>>> Dispatch(application.Children)
<win32com.gen_py.SAP GUI Scripting API.ISapCollectionTarget instance at 0x5752176>
```

**Comment by xoviat** [comment]
I assume we're looking at [`CoClassBaseClass`][1]. You can submit a PR implementing the `__len__` method on that object that simply returns `len(Dispatch(self))` and preferably a test case. Please create the test under tests/win32com in a new file using the py.test format. Do not copy the old tests as they use a deprecated format.

After you have submitted the PR, you should be able to download the whl file from the appveyor "artifacts" tab so you can install it immediately for testing.

[1]: https://github.com/pywin32/pypiwin32/blob/072155f6db5805cdc848f1fcd5647f0ed1e19084/com/win32com/client/__init__.py#L580

**Comment by ronanpaixao** [comment]
I'm not very familiar with win32com's codebase, but I still don't understand why it works in Python 2.7 but doesn't in 3.X. It really shouldn't be just an implementation problem, unless pywin32 uses different codebases for different Python versions.

**Comment by xoviat** [comment]
> It really shouldn't be just an implementation problem, unless pywin32 uses different codebases for different Python versions.

Believe it or not, it does. Previously the code in the repository was Python 2, which was run through 2to3 at setup time. So the Python code was actually different between 2.x/3.x. Currently the code is 3.x. and 2.x is not supported (see 1177ffcb1b6ff14ae58ecd2497d4e5b7fa6b25cd). 

> I'm not very familiar with win32com's codebase,

Personally, you're guess is probably going to be as good as mine. I didn't write most of this code; @mhammond did but he's no longer very active on this project. Put another way: you're probably not going to get a response from him unless you contact him personally. 

The options are really this: you can attempt to find the root cause or you can go with my suggested quick fix. I do not have time to investigate this problem further because I'm involved with other projects. But to reiterate: _your chances of fixing this problem here are much better than anywhere else._

**Comment by mhammond** [comment]
> It really shouldn't be just an implementation problem, unless pywin32 uses different codebases for different Python versions.
> 
> Believe it or not, it does. Previously the code in the repository was Python 2, which was run through 2to3 at setup time. So the Python code was actually different between 2.x/3.x.

As you say, the code is being run through 2to3, but apart from that is the same, so I'm surprised too.

> Currently the code is 3.x. and 2.x is not supported (see 1177ffc).

pywin32 itself still supports both. I'm really not sure why the fork here is making changes unrelated to packaging, and 1177ffc in particular looks very strange. Submitting patches upstream seems to make more sense than doing them in this fork. I expect that I'll soon move the repo from sourceforge to github, and hope to have pypi packaging working some time soonish.

> Personally, you're guess is probably going to be as good as mine. I didn't write most of this code; @mhammond did but he's no longer very active on this project. Put another way: you're probably not going to get a response from him unless you contact him personally.

contacting me directly is fine (as are @mentions here ;), but http://mail.python.org/mailman/listinfo/python-win32 is preferred for general support questions.

> 
> The options are really this: you can attempt to find the root cause or you can go with my suggested quick fix.

The quick fix of adding a len()? At face value that seems wrong.

> I do not have time to investigate this problem further because I'm involved with other projects. But to reiterate: your chances of fixing this problem here are much better than anywhere else.

I don't think that's correct either - I don't understand how changes made here are going to end up in pywin32 itself, either its official repo nor in installers made from it.

**Comment by xoviat** [comment]
> pywin32 itself still supports both. I'm really not sure why the fork here is making changes unrelated to packaging, and 1177ffc in particular looks very strange. Submitting patches upstream seems to make more sense than doing them in this fork. I expect that I'll soon move the repo from sourceforge to github, and hope to have pypi packaging working some time soonish.

That would actually be excellent. 

> pywin32 itself still supports both. I'm really not sure why the fork here is making changes unrelated to packaging, and 1177ffc in particular looks very strange. Submitting patches upstream seems to make more sense than doing them in this fork. I expect that I'll soon move the repo from sourceforge to github, and hope to have pypi packaging working some time soonish.

The only changes that have been made so far here fall into three categories:
1. Alterations to setup.py (the one used here is over 1000 lines less than the original).
2. lib2to3/autopep8
3. specific changes that were apparently required to the C code in order for appveyor to compile (I think these were four lines total).
4. removed adodbapi from repository and added the pypi dependency

I will happily give you the project if you want it but the entire reason for this repository is that when py36 rolled around, I attempted to compile on MSVC 2015, and I received increasingly complex failures. I then looked on the pywin32 bugs and found several users who had been struggling with these problems for months.

When you're running the entire codebase (including setup.py itself) through lib2to3, it's pretty much impossible to debug any errors that occur.

> I don't think that's correct either - I don't understand how changes made here are going to end up in pywin32 itself, either its official repo nor in installers made from it.

They're not. However, consider the following:

1. The installers on sf.net don't work on python 3.6
2. The pywin32 project isn't on pip
3. The pywin32 project is now impossible to compile on a default MSVC 2015 installation.

It's not difficult to deduce that eventually, no one is going to install pywin32 because they simply can't. And if you were to make these changes directly to pywin32, people couldn't benefit from them right away because they couldn't compile the project.

Also, pywin32 doesn't have a CI setup that has testing enabled, so it's impossible to know when problems occur.

I want to be clear that I'm not complaining about pywin32. The amount of time put into it is impressive. But what I'm saying is that my claim that "your chances of fixing this problem here are much better than anywhere else" is definitely supported by the facts and not something that I just made up.

**Comment by ronanpaixao** [comment]
Your suggestion worked only for the `len()` case. It didn't work for other cases like iteration through the container.

What did work was changing [line 539](https://github.com/pywin32/pypiwin32/blob/072155f6db5805cdc848f1fcd5647f0ed1e19084/com/win32com/client/__init__.py#L539) to

```python
		ret = self._ApplyTypes_(*args)
		if isinstance(ret, str):  # Dispatch on string tries to load a library
			return ret
		try:
			return Dispatch(ret)
		except AttributeError:  # Dispatch fails with non-COM variables like int
			return self._ApplyTypes_(*args)
```

But I have no idea how to test this, specially without the application I'm using.

**Comment by xoviat** [comment]
Thanks very much for the patch. I'll apply it to master, but leave this issue open until we have a test.
