### ISSUE TITLE
Placing SendMessageTimeout() outside of win32gui?

### ISSUE THREAD

**Issue by markuskramerIgitt** [pywin32/pypiwin32#60]
A project like [Salt](https://github.com/saltstack/salt) does not open or use any GUI.

On Windows, Salt relies heavily on pywin32, but only the "non-GUI" modules (win32con, win32com, win32net, win32file, win32security, win32api). 
My current understanding is that none of the above modules need a binding to the Microsoft foundation classes (MFC).
The win32gui module, on the other hand, needs MFC binding.

Salt uses exactly one function from the win32gui module: `win32gui.SendMessageTimeout()`.
Its description is "Send a WM_SETTINGCHANGE Broadcast to Windows to refresh the Environment variables"
I believe it has no dependency on MFC.

If that is the case, would you consider placing `SendMessageTimeout()` into another module (e.g. win32api)?
For not breaking other projects, function `win32gui.SendMessageTimeout()` could call `win32api.SendMessageTimeout()`.

With SendMessageTimeout() outside of win32gui, Salt could skip importing the win32gui module. 
Currently, Salt ships the MFC dll library without making any use of it.

Could you please asses or advise?

**Comment by xoviat** [comment]
This is an acceptable change given that it does not break backward compatibility. However, you should know there is lots to be done before the next release and as such it's not going to happen soon. 

If you want you can submit a PR with the requested changes. You need to move the function from `win32/src/win32gui.i` to `win32/src/win32apimodule.cpp`.

**Comment by markuskramerIgitt** [comment]
@xoviat, thank you for your positive assessment. 

I appreciate your hint and will try to submit a PR.

**Comment by xoviat** [comment]
@markuskramerIgitt I've solved this issue in the referenced commits on my branch. However, please note that my branch is currently under factoring and could be rebased (do not commit to it because the history will change).

**Comment by markuskramerIgitt** [comment]
@xoviat, thank you for re-writing PySendMessageTimeout as C++!

**Comment by xoviat** [comment]
@markuskramerIgitt 

Would you mind installing my branch in place of pypiwin32? I really need feedback on what things are broken.

```
pip install git+https://github.com/xoviat/pypiwin32.git@core
pip install git+https://github.com/xoviat/pypiwin32.git@compat
```

**Comment by markuskramerIgitt** [comment]
@xoviat,
I am glad to install your branch and give you feedback.
I will test PySendMessageTimeout.

**Comment by xoviat** [comment]
@markuskramerIgitt Was there any progress on this?

**Comment by markuskramerIgitt** [comment]
@xoviat, shame on me.
I will start immediately.

**Comment by markuskramerIgitt** [comment]
I first need to understand what `SendMessageTimeout` does

I searched SendMessageTimeout in GitHub  and used
```
import win32gui
HWND_BROADCAST      = 0xFFFF
WM_SETTINGCHANGE    = 0x001A
SMTO_ABORTIFHUNG    = 0x0002
sParam              = "Environment"

res1, res2 = win32gui.SendMessageTimeout(HWND_BROADCAST,
              WM_SETTINGCHANGE, 0, sParam, SMTO_ABORTIFHUNG, 100)

print ("result %s, %s from SendMessageTimeout" % (bool(res1), res2))
```
I got `result True, 0 from SendMessageTimeout`, but what is the easiest way to  verify that the function worked?

Then I wanted to run
```
pip install git+https://github.com/xoviat/pypiwin32.git@core
pip install git+https://github.com/xoviat/pypiwin32.git@compat

```

But got this error

```
C:\svn\Magni\how-tos\py>pip install git+https://github.com/xoviat/pypiwin32.git@core
Collecting git+https://github.com/xoviat/pypiwin32.git@core
  Cloning https://github.com/xoviat/pypiwin32.git (to core) to c:\users\markus\appdata\local\temp\pip-iqviti-build
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...

    Installed c:\users\markus\appdata\local\temp\pip-iqviti-build\.eggs\toposort-1.5-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\markus\appdata\local\temp\pip-iqviti-build\setup.py", line 40, in <module>
        from contextlib import suppress
    ImportError: cannot import name suppress

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\markus\appdata\local\temp\pip-iqviti-build\
```

I tried 
```
C:\svn\Magni\how-tos\py>pip install supress
Collecting supress
  Could not find a version that satisfies the requirement supress (from versions: )
No matching distribution found for supress
```

Can you please have a look and suggest what to do?
Thank you,
Markus

**Comment by markuskramerIgitt** [comment]
I also tried `pip install contextlib`, same result.

**Comment by xoviat** [comment]
Unfortunately, pypiwin32-dev doesn't support python 2.7 for the following reasons:

- When I picked this up, the entire codebase was being run through 2to3.
- Python 2.7 support ends in 2020, which is now just three years away.
- Debugging code run through 2to3 is significantly more difficult.
- pypiwin32 is in maintenance mode, meaning that we're not adding new features. this means that Python 2.7 users can simply use older releases and newer pypiwin32 releases can be refactoring for maintainability only. In fact, my goal is to offer even less functionality optionally, because most people will never use scintilla, the executables, or mfc (hence this case).
- Having 2.7 compatibility adds significant maintenance effort and prevents potential optimizations.

It appears that salt now supports Python 3, so this shouldn't be an issue for them moving forward. But unless someone wants to commit their time to 2.7 maintenance, then I simply don't see this feature ever being added because the 2.7 codebase for pypiwin32 is frankly horrific.

**Comment by markuskramerIgitt** [comment]
Hi @xoviat
Thank you for your comprehensive answer - I’ll concentrate on Python3. 
I’m glad you want to refactor into optional parts.

I have successfully `pip installed` your repositories.

These are all me steps directly after installing Python 3.6
```
C:\Python36>Scripts\pip.exe install …\pypiwin32-220-cp36-none-win_amd64.whl
Successfully installed pypiwin32-220

C:\Python36>python.exe …\pypiwin32-wingui-send-messagetimeout.py
result True, 0 from win32gui.SendMessageTimeout

C:\Python36>python.exe …\pypiwin32-winapi-send-messagetimeout.py
Traceback (most recent call last):
  File "…\pypiwin32-winapi-send-messagetimeout.py", line 7, in <module>
    res1, res2 = win32api.SendMessageTimeout(HWND_BROADCAST,
AttributeError: module 'win32api' has no attribute 'SendMessageTimeout'

C:\Python36>Scripts\pip.exe install git+https://github.com/xoviat/pypiwin32.git@core
Successfully installed win32core-0+untagged.4188.gf078cac

C:\Python36>pip install git+https://github.com/xoviat/pypiwin32.git@compat
Successfully installed win32compat-0+untagged.11.g55a42d3

C:\Python36>python.exe pypiwin32-winapi-send-messagetimeout.py
result True, 0 from win32api.SendMessageTimeout
```
**Your patch successfully adds win32api.SendMessageTimeout.**

Unfortunately, I am unable to test it.

I followed http://stackoverflow.com/questions/5898131/set-a-persistent-environment-variable-from-cmd-exe, particularly https://msdn.microsoft.com/en-us/library/ms682653(v=vs.85).aspx

To add a system environment variable I called `regedit` with this script
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment]
"findme"="66"
```
and called SendMessageTimeout, but `echo %findme%` in a second, already opened shell window still returns `%findme%`. In a newly opened shell, the variable is 66.

I tried: 
 - Using win32gui or win32api
 - increased the timeout to 1000


What am I doing wrong?
