### ISSUE TITLE
Can win32file.GetOverlappedResult() return 0?

### ISSUE THREAD

**Issue by altendky** [pywin32/pypiwin32#64]
I'm not sure quite how to read the SWIG here.

https://github.com/pywin32/pypiwin32/blob/0bfdcb303353cabd531c779fc84dafbb3f282022/win32/src/win32file.i#L1291-L1298
```
// @pyswig int|GetOverlappedResult|Determines the result of the most recent call with an OVERLAPPED object.
// @comm The result is the number of bytes transferred.  The overlapped object's attributes will be changed during this call.
BOOLAPI GetOverlappedResult(
	PyHANDLE hFile, 	// @pyparm <o PyHANDLE>|hFile||The handle to the pipe or file
	OVERLAPPED *lpOverlapped, // @pyparm <o PyOVERLAPPED>|overlapped||The overlapped object to check.
	unsigned long *OUTPUT, // lpNumberOfBytesTransferred
	BOOL bWait	// @pyparm int|bWait||Indicates if the function should wait for data to become available.
);
```

Can `win32file.GetOverlappedResult()` return 0?  Or will a 0 return always be 'replaced' by an exception?  I'm trying to figure out if I can get coverage on line 92 below (`if n:`) or if that condition should be removed.

https://codecov.io/gh/twisted/twisted/compare/e62dfb4ee840689fc164f42896f51ef3ad028aab...2c551ff914d3aaf058bf3cac70fbd541bff87f05/src/src/twisted/internet/_win32serialport.py#L92

A naive attempt at coverage by having an empty file being read from resulted in an exception.  Normally this code is run against a serial port but for the sake of unit testing I'm cheating with a regular file.

```
Traceback (most recent call last):
  File "c:\epc\t\613\twisted\src\twisted\internet\test\test_win32serialport.py", line 150, in test_noBytesRead
    port.serialReadEvent()
  File "c:\epc\t\613\twisted\src\twisted\internet\_win32serialport.py", line 91, in serialReadEvent
    n = win32file.GetOverlappedResult(self._serialHandle, self._overlappedRead, 0)
pywintypes.error: (38, 'GetOverlappedResult', 'Reached the end of the file.')
```

Perhaps the answer lies in `win32event.i`, but again, I've never dealt with SWIG.

https://github.com/pywin32/pypiwin32/blob/ad528aeda8d74d2a1566373f9992c9f1d82b126a/SWIG/swig_lib/python/pywintypes.i#L67-L80
```
%typemap(python,out) BOOLAPI {
	$target = Py_None;
	Py_INCREF(Py_None);
}

%typemap(python,except) BOOLAPI {
      Py_BEGIN_ALLOW_THREADS
      $function
      Py_END_ALLOW_THREADS
      if (!$source)  {
           $cleanup
           return PyWin_SetAPIError("$name");
      }
}
```

**Comment by xoviat** [comment]
Here's your c++:

```
static PyObject *_wrap_GetOverlappedResult(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    BOOLAPI  _result;
    PyHANDLE  _arg0;
    OVERLAPPED * _arg1;
    unsigned long * _arg2;
    unsigned long  temp;
    BOOL  _arg3;
    PyObject * _obj0 = 0;
    PyObject * _obj1 = 0;

    self = self;
{
  _arg2 = &temp;
}
    if(!PyArg_ParseTuple(args,"OOi:GetOverlappedResult",&_obj0,&_obj1,&_arg3)) 
        return NULL;
{
	if (!PyWinObject_AsHANDLE(_obj0, &_arg0))
		return NULL;
}
{
	if (!PyWinObject_AsOVERLAPPED(_obj1, &_arg1, TRUE))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (BOOLAPI )GetOverlappedResult(_arg0,_arg1,_arg2,_arg3);

      Py_END_ALLOW_THREADS
      if (!_result)  {
           
           return PyWin_SetAPIError("GetOverlappedResult");
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
    PyObject *o;
    o = PyInt_FromLong((long) (*_arg2));
    if (!_resultobj) {
      _resultobj = o;
    } else if (_resultobj == Py_None) {
      Py_DECREF(Py_None);
      _resultobj = o;
    } else {
      if (!PyList_Check(_resultobj)) {
	PyObject *o2 = _resultobj;
	_resultobj = PyList_New(0);
	PyList_Append(_resultobj,o2);
	Py_XDECREF(o2);
      }
      PyList_Append(_resultobj,o);
      Py_XDECREF(o);
    }
}
    return _resultobj;
}
```

**Comment by altendky** [comment]
If I'm reading it correctly, `if (!_result) {return PyWin_SetAPIError("GetOverlappedResult");}` means that yes, a 0 return from the underlying function will result in an exception and I should eliminate the `if n:` in the Twisted code rather than trying to get test coverage.

**Comment by xoviat** [comment]
I cannot personally say anything about twisted, but yes, PyWin_SetAPIError does return NULL.

**Comment by altendky** [comment]
Thanks for the code and the confirmation.  No point in checking for a 0 return from a function that won't do that.  :]
